In [27]:
import os

print(os.listdir(r"C:\Users\USER\rogii-wellbore-geology-prediction"))

['AI_wellbore_geology_prediction_task_en.pptx', 'sample_submission.csv', 'test', 'train']

In [28]:
import os

files = os.listdir(r"C:\Users\USER\rogii-wellbore-geology-prediction\train")

print("Jumlah file:", len(files))
print(files[:20])

Jumlah file: 2319
['000d7d20.png', '000d7d20__horizontal_well.csv', '000d7d20__typewell.csv', '00bbac68.png', '00bbac68__horizontal_well.csv', '00bbac68__typewell.csv', '00e12e8b.png', '00e12e8b__horizontal_well.csv', '00e12e8b__typewell.csv', '015fe0d2.png', '015fe0d2__horizontal_well.csv', '015fe0d2__typewell.csv', '01869cd4.png', '01869cd4__horizontal_well.csv', '01869cd4__typewell.csv', '01982c1d.png', '01982c1d__horizontal_well.csv', '01982c1d__typewell.csv', '028d7b28.png', '028d7b28__horizontal_well.csv']

In [29]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\train\000d7d20__horizontal_well.csv"
)

print(df.head())
print(df.columns.tolist())
print(df.shape)

        MD           X           Y        Z     ANCC    ASTNU    ASTNL  \
0  11467.0  2983525.16  1069022.09 -9258.57 -9395.81 -9569.86 -9597.64
1  11468.0  2983525.18  1069022.30 -9259.55 -9395.75 -9569.80 -9597.58
2  11469.0  2983525.20  1069022.52 -9260.52 -9395.69 -9569.74 -9597.52
3  11470.0  2983525.22  1069022.73 -9261.50 -9395.64 -9569.69 -9597.47
4  11471.0  2983525.25  1069022.95 -9262.47 -9395.58 -9569.63 -9597.41

     EGFDU    EGFDL     BUDA       TVT          GR  TVT_input
0 -9670.99 -9705.96 -9846.35  11236.02  115.692586   11236.02
1 -9670.93 -9705.90 -9846.29  11237.05  115.584293   11237.05
2 -9670.87 -9705.84 -9846.23  11238.09  135.446960   11238.09
3 -9670.82 -9705.79 -9846.18  11239.12  140.401346   11239.12
4 -9670.76 -9705.73 -9846.12  11240.15  111.270638   11240.15
['MD', 'X', 'Y', 'Z', 'ANCC', 'ASTNU', 'ASTNL', 'EGFDU', 'EGFDL', 'BUDA', 'TVT', 'GR', 'TVT_input']
(5278, 13)

In [30]:
import pandas as pd

test = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\test\000d7d20__horizontal_well.csv"
)

print(test.head())
print(test.columns.tolist())

        MD           X           Y        Z          GR  TVT_input
0  11467.0  2983525.16  1069022.09 -9258.57  115.692586   11236.02
1  11468.0  2983525.18  1069022.30 -9259.55  115.584293   11237.05
2  11469.0  2983525.20  1069022.52 -9260.52  135.446960   11238.09
3  11470.0  2983525.22  1069022.73 -9261.50  140.401346   11239.12
4  11471.0  2983525.25  1069022.95 -9262.47  111.270638   11240.15
['MD', 'X', 'Y', 'Z', 'GR', 'TVT_input']

In [31]:
import pandas as pd

typewell = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\train\000d7d20__typewell.csv"
)

print(typewell.head())
print()
print(typewell.columns.tolist())
print()
print(typewell.shape)

        TVT      GR Geology
0  11223.95  126.11     NaN
1  11224.45  128.22     NaN
2  11224.95  128.72     NaN
3  11225.45  128.12     NaN
4  11225.95  125.29     NaN

['TVT', 'GR', 'Geology']

(1296, 3)

In [32]:
typewell.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TVT      1296 non-null   float64
 1   GR       1296 non-null   float64
 2   Geology  997 non-null    object
dtypes: float64(2), object(1)
memory usage: 30.5+ KB

In [33]:
typewell["Geology"].value_counts(dropna=False)

Geology
ANCC     348
NaN      299
ASTNL    146
EGFDL    121
BUDA      96
LBHL      74
EGFDU     70
ASTNU     56
LTHL      31
LTGT      28
MNSS      27
Name: count, dtype: int64

In [34]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\train\00bbac68__horizontal_well.csv"
)

print(df.columns.tolist())
print(df.shape)

['MD', 'X', 'Y', 'Z', 'ANCC', 'ASTNU', 'ASTNL', 'EGFDU', 'EGFDL', 'BUDA', 'TVT', 'GR', 'TVT_input']
(7559, 13)

In [35]:
import os

files = sorted([
    f for f in os.listdir(
        r"C:\Users\USER\rogii-wellbore-geology-prediction\train"
    )
    if "__horizontal_well.csv" in f
])

print("Total well:", len(files))
print(files[:10])

Total well: 773
['000d7d20__horizontal_well.csv', '00bbac68__horizontal_well.csv', '00e12e8b__horizontal_well.csv', '015fe0d2__horizontal_well.csv', '01869cd4__horizontal_well.csv', '01982c1d__horizontal_well.csv', '028d7b28__horizontal_well.csv', '02e7fe5a__horizontal_well.csv', '0390d174__horizontal_well.csv', '03a935ae__horizontal_well.csv']

In [36]:
import pandas as pd
import os

train_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\train"

files = sorted([
    f for f in os.listdir(train_path)
    if "__horizontal_well.csv" in f
])

dfs = []

for file in files[:10]:
    df = pd.read_csv(os.path.join(train_path, file))

    well_id = file.split("__")[0]
    df["well_id"] = well_id

    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

print(combined_df.shape)
combined_df.head()

(62788, 14)

,MD,X,Y,Z,ANCC,ASTNU,ASTNL,EGFDU,EGFDL,BUDA,TVT,GR,TVT_input,well_id
0,11467.0,2983525.16,1069022.09,-9258.57,-9395.81,-9569.86,-9597.64,-9670.99,-9705.96,-9846.35,11236.02,115.692586,11236.02,000d7d20
1,11468.0,2983525.18,1069022.30,-9259.55,-9395.75,-9569.80,-9597.58,-9670.93,-9705.90,-9846.29,11237.05,115.584293,11237.05,000d7d20
2,11469.0,2983525.20,1069022.52,-9260.52,-9395.69,-9569.74,-9597.52,-9670.87,-9705.84,-9846.23,11238.09,135.446960,11238.09,000d7d20
3,11470.0,2983525.22,1069022.73,-9261.50,-9395.64,-9569.69,-9597.47,-9670.82,-9705.79,-9846.18,11239.12,140.401346,11239.12,000d7d20
4,11471.0,2983525.25,1069022.95,-9262.47,-9395.58,-9569.63,-9597.41,-9670.76,-9705.73,-9846.12,11240.15,111.270638,11240.15,000d7d20

In [37]:
combined_df.isnull().sum()

MD               0
X                0
Y                0
Z                0
ANCC          4430
ASTNU            0
ASTNL            0
EGFDU            0
EGFDL            0
BUDA             0
TVT              0
GR           18197
TVT_input    46484
well_id          0
dtype: int64

In [38]:
combined_df[['ANCC','GR','TVT_input']].isnull().mean()*100

ANCC          7.055488
GR           28.981653
TVT_input    74.033255
dtype: float64

In [39]:
corr = combined_df.select_dtypes(include='number').corr()
corr['TVT'].sort_values(ascending=False)

TVT          1.000000
TVT_input    1.000000
MD           0.440995
X            0.372496
GR           0.295460
Y           -0.673416
EGFDL       -0.945268
EGFDU       -0.946867
ANCC        -0.947617
BUDA        -0.948679
ASTNL       -0.951983
ASTNU       -0.957309
Z           -0.981716
Name: TVT, dtype: float64

In [40]:
features = [
    'MD',
    'X',
    'Y',
    'Z',
    'ANCC',
    'ASTNU',
    'ASTNL',
    'EGFDU',
    'EGFDL',
    'BUDA',
    'GR'
]

In [41]:
target = 'TVT'

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error

In [1]:
features = [
    'MD','X','Y','Z',
    'ANCC','ASTNU','ASTNL',
    'EGFDU','EGFDL','BUDA',
    'GR'
]

data = combined_df[features + ['TVT']].copy()

data = data.fillna(data.median(numeric_only=True))

X = data[features]
y = data['TVT']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

rmse = root_mean_squared_error(y_test, pred)

print("RMSE:", rmse)

NameError: name 'combined_df' is not defined

In [2]:
import pandas as pd
import os

train_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\train"

files = sorted([
    f for f in os.listdir(train_path)
    if "__horizontal_well.csv" in f
])

dfs = []

for file in files[:10]:
    df = pd.read_csv(os.path.join(train_path, file))

    well_id = file.split("__")[0]
    df["well_id"] = well_id

    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

print(combined_df.shape)

(62788, 14)

In [3]:
print(combined_df.shape)

(62788, 14)

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

features = [
    'MD','X','Y','Z',
    'ANCC','ASTNU','ASTNL',
    'EGFDU','EGFDL','BUDA',
    'GR'
]

data = combined_df[features + ['TVT']].copy()

data = data.fillna(data.median(numeric_only=True))

X = data[features]
y = data['TVT']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=20,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, pred))

print("RMSE:", rmse)

RMSE: 0.9837766764727754

In [1]:
import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

NameError: name 'X' is not defined

In [2]:
print(model)

NameError: name 'model' is not defined

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

features = [
    'MD','X','Y','Z',
    'ANCC','ASTNU','ASTNL',
    'EGFDU','EGFDL','BUDA',
    'GR'
]

data = combined_df[features + ['TVT']].copy()

data = data.fillna(data.median(numeric_only=True))

X = data[features]
y = data['TVT']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=20,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, pred))

print("RMSE:", rmse)

NameError: name 'combined_df' is not defined

In [4]:
combined_df

NameError: name 'combined_df' is not defined

In [5]:
import pandas as pd
import os

train_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\train"

files = sorted([
    f for f in os.listdir(train_path)
    if "__horizontal_well.csv" in f
])

dfs = []

for file in files[:10]:
    df = pd.read_csv(os.path.join(train_path, file))

    well_id = file.split("__")[0]
    df["well_id"] = well_id

    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

print(combined_df.shape)

(62788, 14)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

features = [
    'MD','X','Y','Z',
    'ANCC','ASTNU','ASTNL',
    'EGFDU','EGFDL','BUDA',
    'GR'
]

data = combined_df[features + ['TVT']].copy()
data = data.fillna(data.median(numeric_only=True))

X = data[features]
y = data['TVT']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=20,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, pred))

print("RMSE:", rmse)

importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
}).sort_values(
    by='Importance',
    ascending=False
)

print("\nFeature Importance:")
print(importance)

RMSE: 0.9837766764727869

Feature Importance:
   Feature  Importance
3        Z    0.981077
1        X    0.003329
8    EGFDL    0.003155
0       MD    0.003007
7    EGFDU    0.002277
9     BUDA    0.002010
6    ASTNL    0.001999
2        Y    0.001216
5    ASTNU    0.001166
4     ANCC    0.000757
10      GR    0.000005

In [9]:
import os

test_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\test"

print(os.listdir(test_path)[:20])
print("Jumlah file:", len(os.listdir(test_path)))

['000d7d20__horizontal_well.csv', '000d7d20__typewell.csv', '00bbac68__horizontal_well.csv', '00bbac68__typewell.csv', '00e12e8b__horizontal_well.csv', '00e12e8b__typewell.csv']
Jumlah file: 6

In [10]:
import pandas as pd
import os

test_file = os.path.join(
    test_path,
    os.listdir(test_path)[0]
)

df_test = pd.read_csv(test_file)

print(df_test.head())
print(df_test.columns.tolist())
print(df_test.shape)

        MD           X           Y        Z          GR  TVT_input
0  11467.0  2983525.16  1069022.09 -9258.57  115.692586   11236.02
1  11468.0  2983525.18  1069022.30 -9259.55  115.584293   11237.05
2  11469.0  2983525.20  1069022.52 -9260.52  135.446960   11238.09
3  11470.0  2983525.22  1069022.73 -9261.50  140.401346   11239.12
4  11471.0  2983525.25  1069022.95 -9262.47  111.270638   11240.15
['MD', 'X', 'Y', 'Z', 'GR', 'TVT_input']
(5278, 6)

In [11]:
import os

print("TRAIN:")
print(os.listdir(r"C:\Users\USER\rogii-wellbore-geology-prediction\train")[:10])

print("\nTEST:")
print(os.listdir(r"C:\Users\USER\rogii-wellbore-geology-prediction\test")[:10])

TRAIN:
['000d7d20.png', '000d7d20__horizontal_well.csv', '000d7d20__typewell.csv', '00bbac68.png', '00bbac68__horizontal_well.csv', '00bbac68__typewell.csv', '00e12e8b.png', '00e12e8b__horizontal_well.csv', '00e12e8b__typewell.csv', '015fe0d2.png']

TEST:
['000d7d20__horizontal_well.csv', '000d7d20__typewell.csv', '00bbac68__horizontal_well.csv', '00bbac68__typewell.csv', '00e12e8b__horizontal_well.csv', '00e12e8b__typewell.csv']

In [12]:
import pandas as pd

sample = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\sample_submission.csv"
)

print(sample.head())
print(sample.shape)

              id  tvt
0  000d7d20_1442  0.0
1  000d7d20_1443  0.0
2  000d7d20_1444  0.0
3  000d7d20_1445  0.0
4  000d7d20_1446  0.0
(14151, 2)

In [13]:
import pandas as pd

test_df = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\test\000d7d20__horizontal_well.csv"
)

print(test_df.shape)
print(test_df.head())

(5278, 6)
        MD           X           Y        Z          GR  TVT_input
0  11467.0  2983525.16  1069022.09 -9258.57  115.692586   11236.02
1  11468.0  2983525.18  1069022.30 -9259.55  115.584293   11237.05
2  11469.0  2983525.20  1069022.52 -9260.52  135.446960   11238.09
3  11470.0  2983525.22  1069022.73 -9261.50  140.401346   11239.12
4  11471.0  2983525.25  1069022.95 -9262.47  111.270638   11240.15

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

features = [
    'MD',
    'X',
    'Y',
    'Z',
    'GR',
    'TVT_input'
]

data = combined_df[features + ['TVT']].copy()

data = data.fillna(data.median(numeric_only=True))

X = data[features]
y = data['TVT']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model2 = RandomForestRegressor(
    n_estimators=20,
    random_state=42,
    n_jobs=-1
)

model2.fit(X_train, y_train)

pred = model2.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, pred))

print("RMSE:", rmse)

RMSE: 0.6230158269708533

In [15]:
import os
import pandas as pd

test_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\test"

for file in sorted(os.listdir(test_path)):
    if "__horizontal_well.csv" in file:
        df = pd.read_csv(os.path.join(test_path, file))
        print(file, df.shape)

000d7d20__horizontal_well.csv (5278, 6)
00bbac68__horizontal_well.csv (7559, 6)
00e12e8b__horizontal_well.csv (6384, 6)

In [16]:
sample = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\sample_submission.csv"
)

print(sample.head())
print()
print(sample.tail())
print()
print(sample.shape)

              id  tvt
0  000d7d20_1442  0.0
1  000d7d20_1443  0.0
2  000d7d20_1444  0.0
3  000d7d20_1445  0.0
4  000d7d20_1446  0.0

                  id  tvt
14146  00e12e8b_6379  0.0
14147  00e12e8b_6380  0.0
14148  00e12e8b_6381  0.0
14149  00e12e8b_6382  0.0
14150  00e12e8b_6383  0.0

(14151, 2)

In [17]:
sample = pd.read_csv(
    r"C:\Users\USER\rogii-wellbore-geology-prediction\sample_submission.csv"
)

sample['well_id'] = sample['id'].str.split('_').str[0]
sample['row_idx'] = sample['id'].str.split('_').str[1].astype(int)

print(sample.head())

              id  tvt   well_id  row_idx
0  000d7d20_1442  0.0  000d7d20     1442
1  000d7d20_1443  0.0  000d7d20     1443
2  000d7d20_1444  0.0  000d7d20     1444
3  000d7d20_1445  0.0  000d7d20     1445
4  000d7d20_1446  0.0  000d7d20     1446

In [18]:
print(sample['well_id'].value_counts())

well_id
00bbac68    6014
00e12e8b    4301
000d7d20    3836
Name: count, dtype: int64

In [27]:
import pandas as pd
import os

test_path = r"C:\Users\USER\rogii-wellbore-geology-prediction\test"

predictions = {}

In [28]:
print(type(model2))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

In [29]:
for file in os.listdir(test_path):
    if "__horizontal_well.csv" in file:
        print(file)

000d7d20__horizontal_well.csv
00bbac68__horizontal_well.csv
00e12e8b__horizontal_well.csv

In [30]:
file = "000d7d20__horizontal_well.csv"

df_test = pd.read_csv(
    os.path.join(test_path, file)
)

features = [
    'MD',
    'X',
    'Y',
    'Z',
    'GR',
    'TVT_input'
]

pred = model2.predict(df_test[features])

print(len(pred))
print(pred[:5])

5278
[11236.4325 11237.051  11238.0355 11239.1195 11239.8915]

In [31]:
predictions["000d7d20"] = pred

print(predictions.keys())

dict_keys(['000d7d20'])

In [32]:
for file in [
    "00bbac68__horizontal_well.csv",
    "00e12e8b__horizontal_well.csv"
]:

    well_id = file.split("__")[0]

    df_test = pd.read_csv(
        os.path.join(test_path, file)
    )

    pred = model2.predict(
        df_test[features]
    )

    predictions[well_id] = pred

print(predictions.keys())

dict_keys(['000d7d20', '00bbac68', '00e12e8b'])

In [33]:
submission = sample.copy()

submission["tvt"] = submission.apply(
    lambda row: predictions[row["well_id"]][row["row_idx"]],
    axis=1
)

submission = submission[["id", "tvt"]]

print(submission.shape)
submission.head()

(14151, 2)

              id         tvt
0  000d7d20_1442  11747.3820
1  000d7d20_1443  11747.3870
2  000d7d20_1444  11747.3925
3  000d7d20_1445  11747.4025
4  000d7d20_1446  11747.4100

In [35]:
submission.to_csv(
    "submission.csv",
    index=False
)

print("submission.csv done!")

submission.csv done!

In [36]:
import os

print(os.getcwd())

C:\Users\USER

In [37]:
submission.shape

(14151, 2)